// home-screen/src/postDots.jsx
import React, { Component } from 'react';
import solidWhiteDot from './images/solidWhiteDot.png';
import grayDot from './images/grayDot.png';
import './styles.css';

class PostDots extends Component {
    constructor(props) {
        super(props);
    };


    render() {
        const slides = [];
        if (this.props.numSlides>1) {
            for (let i = 0; i < this.props.numSlides; i++) {
                if (i==this.props.currSlide) {
                    slides.push(<img src={solidWhiteDot} style={{height:'0.75em', width:'0.75em'}}/>);
                }
                else {
                    slides.push(<img src={grayDot} style={{height:'0.6em', width:'0.6em'}}/>);
                }
            }
        }
        return (
        <React.Fragment>
        <div style={{display:'flex', width:'100%', position:'absolute', top:'95%', justifyContent:'center', alignItems:'start',  gap:'0.2em'}}>
        {slides}
        </div>
        </React.Fragment>);
    };
}

export default PostDots;

// vuejs-frontend1/src/components/PostDots.vue
<template>
    <div :style="{display: 'flex', width: '100%', position: 'absolute', top: currSlideIsImage ? '95%' : '90%', left: '0%',
    justifyContent: 'center', alignItems: 'center', gap: '0.2em', zIndex: '10'}">
        <img v-for="(_, index) in numSlides"
            :key="index"
            :src="index == currSlide ? solidWhiteDot : grayDot"
            :style="{height: index == currSlide ? '0.9em' : '0.6em', width: index == currSlide ?
            '0.9em' : '0.6em', marginBottom: index == currSlide ? '-0.1em' : '', pointerEvents: 'none'}"
        />
    </div>
</template>
  

<script setup>
    import grayDot from '../assets/images/grayDot.png';
import solidWhiteDot from '../assets/images/solidWhiteDot.png';

    import { defineProps } from 'vue';

    
    const props = defineProps({
        currSlide: Number,
        numSlides: Number
    });
</script>
