// vuejs-frontend1/src/components/AccountPreview.vue
<template>
    <div class="popup" :style="{width:'22em', position:'absolute', padding: '1.5em 1.5em', borderRadius:'2%',
    zIndex: '10'}">
        <div :style="{display:'flex', justifyContent:'start', alignItems:'start'}">
            <a :href="'http://34.111.89.101/profile/' + username" target="_blank" rel="noopener noreferrer">
                <img :src="userPfp" :style="{width:'3em', height:'3em', cursor: 'pointer'}"/>
            </a>
  
            <div :style="{display:'flex', flexDirection:'column', marginLeft:'0.7em',
            alignItems: 'start'}">
                <div :style="{display: 'flex', alignItems: 'center'}">
                    <a :href="'http://34.111.89.101/profile/' + username" :style="{fontSize:'0.85em', cursor:'pointer',
                    maxWidth: '10em', overflowWrap:'break-word', fontWeight: 'bold', textAlign: 'start'}"
                    target="_blank" rel="noopener noreferrer">
                        {{ username }}
                    </a>
  
                    <img v-if="userIsVerified" :src="verifiedBlueCheck" :style="{pointerEvents: 'none', height: '1.5em',
                    width: '1.5em', objectFit: 'contain'}"/>
                </div>
    
                <p :style="{fontSize:'0.8em', color:'#787878', maxWidth: '12em', overflowWrap:'break-word', textAlign:
                'start'}">
                    {{ userFullName }}
                </p>
            </div>
        </div>
  
        <div :style="{display:'flex', width: '100%', justifyContent: 'space-between',
        alignItems: 'end', marginTop: '1em'}">
            <div :style="{display: 'flex', flexDirection: 'column', alignItems: 'center'}">
                <b :style="{maxWidth: '3em', overflowWrap: 'break-word', marginBottom: '-1em'}">
                    {{ formatNumber(numPosts) }}
                </b>
                <p>posts</p>
            </div>
            <div :style="{display: 'flex', flexDirection: 'column', alignItems: 'center'}">
                <b :style="{maxWidth: '3em', overflowWrap: 'break-word', marginBottom: '-1em'}">
                    {{ formatNumber(numFollowers) }}
                </b>
                <p>followers</p>
            </div>
            <div :style="{display: 'flex', flexDirection: 'column', alignItems: 'center'}">
                <b :style="{maxWidth: '3em', overflowWrap: 'break-word', marginBottom: '-1em'}">
                    {{ formatNumber(numFollowings) }}
                </b>
                <p>following</p>
            </div>
        </div>
  
        <br/>
        <br/>
  
        <div v-if="userIsPrivate==true" :style="{display:'flex', flexDirection: 'column', alignItems: 'center'}">
            <img :src="privateAccount" :style="{height:'7em', width:'7em', objectFit:'contain', pointerEvents: 'none'}"/>
            <b>
                This account is private
            </b>
            <p :style="{color:'gray', fontSize:'0.8em', marginTop:'0.1em'}">
                Follow them to see their photos and videos.
            </p>
        </div>
  
        <a v-if="userIsPrivate==false || userIsPrivate === '?'" :href="'http://34.111.89.101/profile/' + username"
        :style="{fontSize: '0.84em', color: '#666666', cursor: 'pointer'}" target="_blank" rel="noopener noreferrer">
            Click here to visit this user's profile.
        </a>
  
        <br/>
        <br/>
  
        <button @click="toggleFollowUser" class="blueButton" :style="{width:'107%', backgroundColor: toggleFollowText ===
        'Follow' ? '#327bf0' : '#f5f5f5', color: toggleFollowText === 'Follow' ? '' : 'black', cursor:'pointer',
        marginLeft: '-0.8em'}">
            {{ toggleFollowText }}
        </button>
    </div>
</template>


<script setup>
    import privateAccount from "../assets/images/privateAccount.png";
import verifiedBlueCheck from '../assets/images/verifiedBlueCheck.png';

    import { defineProps } from 'vue';


    const props = defineProps({
        username: String,
        userPfp: String,
        userFullName: String,
        toggleFollowText: String,

        authUserId: Number,
        userId: Number,
        numPosts: Number,
        numFollowers: Number,
        numFollowings: Number,

        userIsVerified: Boolean,
        
        userIsPrivate: Object,

        updateFollowText: Function,
        showErrorPopup: Function
    });


    function formatNumber(number) {
        if(number == -1) {
            return '?';
        }
        else if (number < 10000) {
            return number.toLocaleString();
        }
        else if (number >= 10000 && number < 1000000) {
            return (number / 1000).toFixed(1).replace(/\.0$/, '') + 'K';
        }
        else if (number >= 1000000 && number < 1000000000) {
            return (number / 1000000).toFixed(1).replace(/\.0$/, '') + 'M';
        }
        else if (number >= 1000000000 && number < 1000000000000) {
            return (number / 1000000000).toFixed(1).replace(/\.0$/, '') + 'B';
        }
        else {
            return (number / 1000000000000).toFixed(1).replace(/\.0$/, '') + 'T';
        }
    }


    async function toggleFollowUser() {
        if (props.authUserId == -1) {
            props.showErrorPopup('Dear Anonymous Guest, you must be logged in to an account to do that');
            return;
        }

        const usernameToToggleFollow = props.username;
        const userIdToToggleFollow = props.userId;

        try {
            const response = await fetch('http://34.111.89.101/api/Home-Page/djangoBackend2/graphql', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({
                    query: `query toggleFollowUser($authUserId: Int!, $userIdToToggleFollow: Int!) {
                        toggleFollowUser(authUserId: $authUserId, userIdToToggleFollow: $userIdToToggleFollow)
                    }`,
                    variables: {
                        authUserId: props.authUserId,
                        userIdToToggleFollow: userIdToToggleFollow
                    }
                }),
                credentials: 'include'
            });
            if(!response.ok) {
                props.showErrorPopup(
                    `The server had trouble toggling your follow-status of user ${usernameToToggleFollow}`
                );
            }
            else {
                let newFollowingStatus = await response.json();
                newFollowingStatus = newFollowingStatus.data.toggleFollowUser;

                if (newFollowingStatus==='Stranger') {
                    props.updateFollowText('Follow');
                }
                else if(newFollowingStatus==='Following') {
                    props.updateFollowText('Unfollow');
                }
                else {
                    props.updateFollowText('Cancel Request');
                }
            }
        }
        catch (error) {
            props.showErrorPopup(`There was trouble connecting to the server to toggle your follow-status of
            user ${usernameToToggleFollow}`);
        }
    }
</script>

// home-screen/src/accountPreview.jsx
import React, { Component } from 'react';
import profileIcon from "./images/profileIcon.png";
import privateAccount from "./images/privateAccount.png";
import './styles.css';


class AccountPreview extends Component {
    constructor(props) {
        super(props);
        this.state = {
        }
    };


    translateTextPromise = async function(text, language1, language2){
        let language1Code;
        let language2Code;
        if(language1===language2) {
            return text;
        }
        if (language1==="English"){
            language1Code = "en";
        }
        else if(language1==="Español") {
            language1Code = "es";
        }
        else if(language1==="Français") {
            language1Code = "fr";
        }
        else if(language1==="हिंदी") {
            language1Code = "hi";
        }
        else if(language1==="中国人") {
            language1Code = "zh-CN";
        }
        else if(language1==="বাংলা"){
            language1Code = "bn";
        }
        else if(language1==="العربية") {
            language1Code = "ar";
        }
        else if(language1==="Deutsch") {
            language1Code = "de";
        }
        else if(language1==="Bahasa Indonesia") {
            language1Code = "id";
        }
        else if(language1==="Italiano"){
            language1Code = "it";
        }
        else if(language1==="日本語") {
            language1Code = "ja";
        }
        else if(language1==="Русский") {
            language1Code = "ru";
        }
        if (language2==="English"){
            language2Code = "en";
        }
        else if(language2==="Español") {
            language2Code = "es";
        }
        else if(language2==="Français") {
            language2Code = "fr";
        }
        else if(language2==="हिंदी") {
            language2Code = "hi";
        }
        else if(language2==="中国人") {
            language2Code = "zh-CN";
        }
        else if(language2==="বাংলা"){
            language2Code = "bn";
        }
        else if(language2==="العربية") {
            language2Code = "ar";
        }
        else if(language2==="Deutsch") {
            language2Code = "de";
        }
        else if(language2==="Bahasa Indonesia") {
            language2Code = "id";
        }
        else if(language2==="Italiano"){
            language2Code = "it";
        }
        else if(language2==="日本語") {
            language2Code = "ja";
        }
        else if(language2==="Русский") {
            language2Code = "ru";
        }
        const apiUrl = "https://deep-translate1.p.rapidapi.com/language/translate/v2";
        const data = {"q":text,"source":language1Code,"target":language2Code};
        const options = {
            method: 'POST',
            headers: {
            'Content-Type': 'application/json',
            'x-rapidapi-host': 'deep-translate1.p.rapidapi.com',
            'x-rapidapi-key': '14da2e3b7emsh5cd3496c28a4400p16208cjsn947339fe37a4'
            },
            body: JSON.stringify(data)
        };
        try {
            const response = await fetch(apiUrl, options);
            if (!response.ok) {
                throw new Error("Network response not ok");
            }
            return response.json()['data']['translations']['translatedText'];
        }

        catch (error) {
            console.error('Error:', error);
            return "T";
        }
    }



    render() {
        return (
        <React.Fragment>
        <div class="popup" style={{backgroundColor:"white", width:'22em', height:'22em', position:'absolute', zIndex:'3',
        paddingTop:'2em', paddingLeft:'2em', borderRadius:'2%'}}>
        <div style={{display:'flex', justifyContent:'start', alignItems:'start'}}>
        <img src={profileIcon} style={{width:'3em', height:'3em'}}/>
        <div style={{display:'flex', flexDirection:'column', justifyContent:'center', alignItems:'start', marginLeft:'0.7em'}}>
        <p style={{fontWeight:'bold', fontSize:'0.85em', cursor:'pointer'}}>{this.props.username}</p>
        <p style={{fontSize:'0.7em', marginTop:'-0.7em', color:'#787878'}}>{this.props.fullName}</p>
        </div>
        </div>
        <div style={{position:'absolute', top:'30%', display:'flex', gap:'7em', marginLeft:'1.5em', fontWeight:'bold'}}>
        <span>{this.props.numPosts}</span>
        <span>{this.props.numFollowers}</span>
        <span>{this.props.numFollowing}</span>
        </div>
        <div style={{position:'absolute', top:'40%', display:'flex', gap:'6em', marginLeft:'0.5em', marginTop:'-0.3em',
        fontSize:'0.9em'}}>
        <span>posts</span>
        <span>followers</span>
        <span>following</span>
        </div>
        {this.props.isPrivate && (<div style={{position:'absolute', top:'45%', display:'flex', flexDirection: 'column'}}>
        <img src={privateAccount} style={{height:'7em', width:'7em', objectFit:'contain', marginLeft:'6.4em'}}/>
        <b style={{marginLeft:'0.4em'}}>This account is private</b>
        <p style={{color:'gray', fontSize:'0.8em', marginLeft:'0.4em', marginTop:'0.1em'}}>Follow this account to see their photos and videos.</p>
        </div>)}
        <button className="blueButton" style={{width:'27em', backgroundColor:'#327bf0', position:'absolute', top:'81.5%', marginLeft:'-15em', cursor:'pointer'}}>Follow</button>
        </div>
        </React.Fragment>);
    };
}

export default AccountPreview;
