// vuejs-frontend1/src/components/FollowUser.vue
<template>
    <div class="selectUserOrGroupChat" :style="{width: '95%', display: 'flex', alignItems: 'center', justifyContent:
    'space-between', boxShadow: 'none', padding: '0.5em 1em'}">
        <div :style="{ display: 'flex', alignItems: 'start' }">
            <a :href="'http://34.111.89.101/profile/' + username" target="_blank" rel="noopener noreferrer">
                <img :src="userPfp" :style="{objectFit: 'contain', height: '3em', width: '3em', cursor: 'pointer'}" />
            </a>

            <div :style="{display: 'flex', flexDirection: 'column', alignItems: 'start', marginLeft: '1em'}">
                <div :style="{ display: 'flex', alignItems: 'center' }">
                    <b :style="{maxWidth: '10em', overflowWrap: 'break-word', cursor: 'pointer', textAlign: 'start',
                    fontWeight: 'bold'}">
                        {{ username }}
                    </b>
                    <img v-if="userIsVerified" :src="verifiedBlueCheck" :style="{pointerEvents: 'none', height: '1.5em',
                    width: '1.5em', objectFit: 'contain'}"/>
                </div>

                <p :style="{maxWidth: '10em', overflowWrap: 'break-word', color: 'gray', marginTop: '0.5em', textAlign: 'start'}">
                    {{ userFullName === '?' ? 'Could not get full name' : userFullName }}
                </p>
            </div>
        </div>
    
        <button @click="toggleFollowUser" :style="{backgroundColor: toggleFollowText !== 'Follow' ? '#f5f5f5' : '#1f86ed',
        color: toggleFollowText !== 'Follow' ? 'black' : 'white', fontWeight: 'bold', cursor: 'pointer', borderStyle: 'none',
        width: '10em', borderRadius: '0.5em', paddingLeft: '0.5em', paddingBottom: '0.5em', paddingTop: '0.5em'}">
            {{ toggleFollowText }}
        </button>
    </div>
</template>
  


<script>
    import verifiedBlueCheck from '../assets/images/verifiedBlueCheck.png';


    export default {
        props: {
            authUserId: Number,
            userId: Number,

            username: String,
            userFullName: String,
            userPfp: String,
            originalFollowText: String,

            userIsVerified: Boolean,

            showErrorPopup: Function
        },


        data() {
            return {
                verifiedBlueCheck,

                toggleFollowText: ''
            }
        },


        mounted() {
            this.toggleFollowText = this.originalFollowText;
        },


        methods: {
            async toggleFollowUser() {
                if (this.authUserId === -1) {
                    this.showErrorPopup(`You cannot toggle your follow-status of user ${this.username} when you are on 'Anonymous
                    Guest' mode`);
                    return;
                }

                try {
                    const response = await fetch('http://34.111.89.101/api/Home-Page/djangoBackend2/graphql', {
                        method: 'POST',
                        headers: {'Content-Type': 'application/json'},
                        body: JSON.stringify({
                            query: `query toggleFollowUser($authUserId: Int!, $userIdToToggleFollow: Int!) {
                                toggleFollowUser(authUserId: $authUserId, userIdToToggleFollow: $userIdToToggleFollow)
                            }`,
                            variables: {
                                authUserId: this.authUserId,
                                userIdToToggleFollow: this.userId
                            }
                        }),
                        credentials: 'include'
                    });
                    if(!response.ok) {
                        this.showErrorPopup(`The server had trouble toggling your follow-status of user ${this.username}`);
                    }
                    else {
                        let newFollowingStatus = await response.json();
                        newFollowingStatus = newFollowingStatus.data.toggleFollowUser;

                        if(newFollowingStatus === 'Stranger') {
                            newFollowingStatus = 'Follow';
                        }
                        this.toggleFollowText = newFollowingStatus;
                    }
                }

                catch (error) {
                    this.showErrorPopup(`There was trouble connecting to the server to toggle your follow-status of user
                    ${this.username}`);
                }
            }
        }
    };
</script>

// home-screen/src/followUser.jsx
import React, { Component } from 'react';
import profileIcon from './images/profileIcon.png';
import moreIcon from './images/moreIcon.png';
import solidWhiteDot from './images/solidWhiteDot.png';
import checkedIcon from './images/checkedIcon.png';
import './styles.css';

class FollowUser extends Component {
    constructor(props) {
        super(props);
        this.state = {
            isHovering: false,
            error: null,
            profilePhoto: null,
            profilePhotoLoading: true,
            isFollowing: true,
        }
    };

    handleMouseEnter = () => {
        this.setState({isHovering: true})
    }

    handleMouseLeave = () => {
        this.setState({isHovering: false})
    }


    fetchProfilePhoto(username) {
        fetch(`http://localhost:8003/getProfilePhoto/${username}`)
            .then(response => {
                if (!response.ok) {
                    this.setState({
                        error: true,
                        profilePhotoLoading: false
                    });
                    throw new Error('Network response was not ok');
                }
                return response.arrayBuffer();
            })
            .then(buffer => {
                const base64Flag = 'data:image/jpeg;base64,';
                const imageStr = this.arrayBufferToBase64(buffer);
                this.setState({
                    profilePhoto: base64Flag + imageStr,
                    profilePhotoLoading: false
                });
            })
            .catch(error => {
                this.setState({
                    error: true,
                    profilePhotoLoading: false
                });
            });
    }

    arrayBufferToBase64(buffer) {
        let binary = '';
        const bytes = new Uint8Array(buffer);
        const len = bytes.byteLength;
        for (let i = 0; i < len; i++) {
            binary += String.fromCharCode(bytes[i]);
        }
        return window.btoa(binary);
    }

    async componentDidMount() {
        this.fetchProfilePhoto(this.props.username);
    }

    async componentDidUpdate(prevProps, prevState) {
        if(prevState.isFollowing != this.props.isFollowing) {
            this.setState({isFollowing: this.props.isFollowing});
        }
    }

    toggleFollow = () => {
        this.setState({isFollowing: !this.state.isFollowing});
    }


    render() {
        return (
        <React.Fragment>
        <div className="popup" onMouseEnter={this.handleMouseEnter} onMouseLeave={this.handleMouseLeave} style={{cursor:'pointer', width:'95%', display:'flex', alignItems:'center',
        backgroundColor: this.state.isHovering ? '#ebedeb' : 'white', justifyContent:'space-between', boxShadow:'none'}}>
        <div style={{display:'flex', alignItems:'start'}}>
        {!(this.state.profilePhotoLoading || this.state.error) &&
        <img src={this.state.profilePhoto} style={{objectFit:'contain', height:'3em', width:'3em'}}/>}
        {(this.state.profilePhotoLoading || this.state.error) &&
        <img src={this.state.moreIcon} style={{objectFit:'contain', height:'3em', width:'3em'}}/>}
        <div style={{display:'flex', flexDirection:'column', alignItems:'start', marginLeft:'1em'}}>
        <p>{this.props.username}</p>
        <br/>
        </div>
        </div>
        {this.state.isFollowing && !this.props.isOwn &&
        <button onClick={this.toggleFollow} style={{backgroundColor:'#f5f5f5', color:'black', fontWeight:'bold', cursor:'pointer',
        borderStyle:'none', width:'10em', borderRadius:'0.5em', paddingLeft:'0.5em', paddingBottom:'0.5em', paddingTop:'0.5em'}}>Following</button>}
        {!this.state.isFollowing && !this.props.isOwn &&
        <button onClick={this.toggleFollow} style={{backgroundColor:'#1f86ed', fontWeight:'bold', color:'white', cursor:'pointer',
        borderStyle:'none', width:'8em', borderRadius:'0.5em', paddingLeft:'0.5em', paddingBottom:'0.5em', paddingTop:'0.5em'}}>Follow</button>}
        </div>
        </React.Fragment>);
    };
}

export default FollowUser;
