// vuejs-frontend1/src/views/HomePage.vue
<template>
    <LeftSidebar
        :profilePhoto="defaultPfp"
        :displayPopup="displayLeftSidebarPopup"
        :authUserIsAnonymousGuest="authUserId == -1"
        :toggleDisplayPopup="toggleDisplayLeftSidebarPopup"
    />


    <div style="position: absolute; left: 74%;">
        
    </div>

    <img v-if="displayLeftSidebarPopup || displayErrorPopup || displayThreeDotsPopup || displayAboutAccountPopup ||
    displayLikersPopup || displaySendPostPopup" @click="closeAllPopups" :src="blackScreen" style="position: fixed; top: 0%; left: 0%;
    width: 100%; height: 100%; opacity: 0.7; zIndex: 2;"/>

    <div v-if="displayAboutAccountPopup" :style="[
        { position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)' },
        { zIndex: displayStoryViewer ? '1' : '3' }
    ]">
        <AboutAccountPopup
            :authUserId="authUserId"
            :userId="aboutAccountUserId"
            :username="aboutAccountUsername"
            :authUser="authUser"
            :userPfp="aboutAccountUserProfilePhoto"
            :userIsVerified="aboutAccountUserIsVerified"
            :userHasStories="aboutAccountUserHasStories"
            :userHasUnseenStory="aboutAccountUserHasUnseenStory"
            :usersAndTheirRelevantInfo="usersAndTheirRelevantInfo"
            :addRelevantInfoToUser="addRelevantInfoToUser"
            :closePopup="closeAboutAccountPopup"
            :showStoryViewer="showStoryViewer"
        />
    </div>

    <div v-if="displayLeftSidebarPopup" :style="[
        { position: 'fixed', bottom: '10%', left: '1%' },
        { zIndex: displayErrorPopup ? '1' : '3' }
    ]">
        <LeftSidebarPopup
            :authUserId="authUserId"
            :originalURL="originalURL"
            :showErrorPopup="showErrorPopup"
        />
    </div>

    <div v-if="displayThreeDotsPopup" :style="[
        { position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)' },
        { zIndex: displayErrorPopup ? '1' : '3' }
    ]">
        <ThreeDotsPopup
            :authUserId="authUserId"
            :postDetails="threeDotsPopupPostDetails"
            :hidePost="hidePost"
            :showErrorPopup="showErrorPopup"
            :closePopup="closeThreeDotsPopup"
            :showAboutAccountPopup="showAboutAccountPopup"
        />
    </div>

    <div v-if="displayLikersPopup" :style="[
        { position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)' },
        { zIndex: displayErrorPopup ? '1' : '3' }
    ]">
        <LikersPopup
            :idOfPostOrComment="likersPopupIdOfPostOrComment"
            :authUserId="authUserId"
            :usersAndTheirRelevantInfo="usersAndTheirRelevantInfo" 
            :closePopup="closeLikersPopup"
            :showErrorPopup="showErrorPopup"
            :updateUsersAndTheirRelevantInfo="updateUsersAndTheirRelevantInfo"
        />
    </div>

    <div v-if="displaySendPostPopup" :style="[
        { position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)' },
        { zIndex: displayErrorPopup ? '1' : '3' }
    ]">
        <SendPostPopup
            :authUserId="authUserId"
            :overallPostId="sendPostPopupOverallPostId"
            :usersAndTheirRelevantInfo="usersAndTheirRelevantInfo"
            :cachedMessageSendingSuggestions="cachedMessageSendingSuggestions"
            :updateUsersAndTheirRelevantInfo="updateUsersAndTheirRelevantInfo"
            :updateCachedMessageSendingSuggestions="updateCachedMessageSendingSuggestions"
            :showErrorPopup="showErrorPopup"
            :closePopup="closeSendPostPopup"
        />
    </div>

    <div v-if="displayErrorPopup" style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); zIndex:
    3;">
        <ErrorPopup
            :errorMessage="errorPopupMessage"
            :closePopup="closeErrorPopup"
        />
    </div>
</template>


<script>
    import AboutAccountPopup from '@/components/Popups/AboutAccountPopup.vue';
import ErrorPopup from '@/components/Popups/ErrorPopup.vue';
import LeftSidebarPopup from '@/components/Popups/LeftSidebarPopup.vue';
import LikersPopup from '@/components/Popups/LikersPopup.vue';
import SendPostPopup from '@/components/Popups/SendPostPopup.vue';
import ThreeDotsPopup from '@/components/Popups/ThreeDotsPopup.vue';

    //import FooterSection from '@/components/FooterSection.vue';
    import LeftSidebar from '@/components/LeftSidebar.vue';
//import UserIcon from '@/components/UserIcon.vue';
//import UserBar from '@/components/UserBar.vue';

    import blackScreen from '@/assets/images/blackScreen.png';
import defaultPfp from '@/assets/images/defaultPfp.png';

    import '../assets/HomePageStyles.css';


    export default {
        components: {
            LeftSidebarPopup,
            ErrorPopup,
            ThreeDotsPopup,
            AboutAccountPopup,
            LikersPopup,
            SendPostPopup,

            LeftSidebar,
            //FooterSection,
            //UserIcon,
            //UserBar,
        },


        data() {
            return {
                defaultPfp,
                blackScreen,

                authUser: '',
                authUserId: -1,

                originalURL: '',
                numTimesRouteParamsWasWatched: 0,

                displayLeftSidebarPopup: false,

                displayErrorPopup: false,
                errorPopupMessage: '',

                displayThreeDotsPopup: false,
                threeDotsPopupPostDetails: {},

                displayAboutAccountPopup: false,
                aboutAccountUsername: '',
                aboutAccountUserId: -1,
                aboutAccountUserIsVerified: false,
                aboutAccountUserHasStories: false,
                aboutAccountUserHasUnseenStory: false,
                aboutAccountUserProfilePhoto: null,

                displayLikersPopup: false,
                likersPopupIdOfPostOrComment: '',

                displaySendPostPopup: false,
                sendPostPopupOverallPostId: '',

                displayCommentsPopup: false,

                displayStoryViewer: false,
                storyViewerUsername: '',
                storyViewerIsFromStoriesSection: false,

                usersAndTheirRelevantInfo: {},

                cachedMessageSendingSuggestions: {},

                orderedListOfPosts: []
            }
        },


        mounted() {
            this.originalURL = window.location.href;
        },


        methods: {
            async authenticateUser(username, userId) {
                if (userId == null) {
                    try {
                        const response = await fetch('http://34.111.89.101/api/Home-Page/laravelBackend1/graphql', {
                            method: 'POST',
                            headers: {'Content-Type': 'application/json'},
                            body: JSON.stringify({
                                query: `query getUserIdOfUsername($username: String!) {
                                    getUserIdOfUsername(username: $username)
                                }`,
                                variables: {
                                    username: username
                                }
                            })
                        });
                        if (!response.ok) {
                            this.authUser = 'Anonymous Guest';

                            throw new (
                                `The laravelBackend1 server had trouble getting the user-id of username ${username}`
                            );
                        }
                        userId = await response.json();
                        this.authUserId = userId;
                    }
                    catch {
                        this.authUser = 'Anonymous Guest';

                        throw new Error(
                            `There was trouble connecting to the laravelBackend1 server to get the user-id of username
                            ${username}`
                        );
                    }
                }
                else {
                    this.authUserId = userId;
                }

                try {
                    const response1 = await fetch(`http://34.111.89.101/api/Home-Page/expressJSBackend1/authenticateUser
                    /${userId}`, {
                        credentials: 'include'
                    });
                    if (!response1.ok) {
                        this.authUser = 'Anonymous Guest';
                        this.authUserId = -1;

                        throw new Error(
                            `The expressJSBackend1 server had trouble verifying you as having the proper credentials to
                            be logged in as user ${userId}`
                        );
                    }

                    this.authUser = username;
                }
                catch {
                    this.authUser = 'Anonymous Guest';
                    this.authUserId = -1;

                    throw new Error(
                        `There was trouble connecting to the expressJSBackend1 server to verify you as having the proper
                        credentials to be logged in as user ${userId}`
                    );
                }
            },


            async fetchStories() {

            },


            async fetchSuggestedAccounts() {

            },


            async fetchPosts(initialOrAdditionalText) {
                initialOrAdditionalText;
            },


            hidePost() {
                this.orderedListOfPosts = this.orderedListOfPosts.filter(
                    postDetails => (postDetails.overallPostId !== this.threeDotsPopupPostDetails.overallPostId)
                );
                this.displayThreeDotsPopup = false;
                this.displayCommentsPopup = false;
            },


            updateUsersAndTheirRelevantInfo(newUsersAndTheirRelevantInfo) {
                this.usersAndTheirRelevantInfo = newUsersAndTheirRelevantInfo;
            },


            updateCachedMessageSendingSuggestions(newCachedMessageSendingSuggestions) {
                this.cachedMessageSendingSuggestions = newCachedMessageSendingSuggestions;
            },


            showErrorPopup(newErrorPopupMessage) {
                this.errorPopupMessage = newErrorPopupMessage;
                this.displayErrorPopup = true;
            },

            
            showAboutAccountPopup(newAboutAccountUsername, newAboutAccountUserId) {
                this.aboutAccountUsername = newAboutAccountUsername;
                this.aboutAccountUserId = newAboutAccountUserId;

                this.aboutAccountUserIsVerified = 
                    newAboutAccountUserId in this.usersAndTheirRelevantInfo &&
                    'isVerified' in this.usersAndTheirRelevantInfo[newAboutAccountUserId]
                    ? this.usersAndTheirRelevantInfo[newAboutAccountUserId].isVerified
                    : false;

                this.aboutAccountUserHasStories = 
                    newAboutAccountUserId in this.usersAndTheirRelevantInfo &&
                    'hasStories' in this.usersAndTheirRelevantInfo[newAboutAccountUserId]
                    ? this.usersAndTheirRelevantInfo[newAboutAccountUserId].hasStories
                    : false;

                this.aboutAccountUserHasUnseenStory = 
                    newAboutAccountUserId in this.usersAndTheirRelevantInfo &&
                    'hasUnseenStory' in this.usersAndTheirRelevantInfo[newAboutAccountUserId]
                    ? this.usersAndTheirRelevantInfo[newAboutAccountUserId].hasUnseenStory
                    : false;

                this.aboutAccountUserProfilePhoto = 
                    newAboutAccountUserId in this.usersAndTheirRelevantInfo &&
                    'profilePhoto' in this.usersAndTheirRelevantInfo[newAboutAccountUserId]
                    ? this.usersAndTheirRelevantInfo[newAboutAccountUserId].profilePhoto
                    : defaultPfp;

                this.displayAboutAccountPopup = true;
            },

            
            showStoryViewer(newStoryViewerUsername, newStoryViewerIsFromStoriesSection) {
                this.storyViewerUsername = newStoryViewerUsername;
                this.storyViewerIsFromStoriesSection = newStoryViewerIsFromStoriesSection;
                this.displayStoryViewer = true;
            },


            showLikersPopup(newLikersPopupIdOfPostOrComment) {
                this.likersPopupIdOfPostOrComment = newLikersPopupIdOfPostOrComment;
                this.displayLikersPopup = true;
            },


            showSendPostPopup(newSendPostPopupOverallPostId) {
                this.sendPostPopupOverallPostId = newSendPostPopupOverallPostId;
                this.displaySendPostPopup = true;
            },


            toggleDisplayLeftSidebarPopup() {
                this.displayLeftSidebarPopup = !this.displayLeftSidebarPopup;
            },


            closeAllPopups() {
                if(!(this.displayCommentsPopup && (this.displayThreeDotsPopup || this.displayAboutAccountPopup ||
                this.displayErrorPopup || this.displayLikersPopup || this.displaySendPostPopup))) {
                    this.displayCommentsPopup = false;
                }

                this.displayLeftSidebarPopup = false;
                this.displayErrorPopup = false;
                this.displayThreeDotsPopup = false;
                this.displayAboutAccountPopup = false;
                this.displayLikersPopup = false;
                this.displaySendPostPopup = false;
            },


            closeErrorPopup() {
                this.displayErrorPopup = false;
            },


            closeThreeDotsPopup() {
                this.displayThreeDotsPopup = false;
            },


            closeAboutAccountPopup() {
                this.displayAboutAccountPopup = false;
                this.displayThreeDotsPopup = false;
            },


            closeLikersPopup () {
                this.displayLikersPopup = false;
            },


            closeSendPostPopup() {
                this.displaySendPostPopup = false;
            },


            addRelevantInfoToUser(userId, userFieldsAndTheirValues) {
                if (!(userId in this.usersAndTheirRelevantInfo)) {
                    this.usersAndTheirRelevantInfo[userId] = {};
                }

                for(let field of Object.keys(userFieldsAndTheirValues)) {
                    this.usersAndTheirRelevantInfo[userId][field] = userFieldsAndTheirValues[field];
                }
            }
        },


        watch: {
            '$route.params': {
                immediate: true,
                handler(newRouteParams) {
                    this.numTimesRouteParamsWasWatched++;
                    if(this.numTimesRouteParamsWasWatched<2) {
                        return;
                    }

                    if (typeof newRouteParams.username !== 'undefined' && localStorage.getItem('defaultUsername') !==
                    newRouteParams.username) {
                        this.authenticateUser(newRouteParams.username, null);
                    }
                    else if (localStorage.getItem('defaultUsername')) {
                        if (localStorage.getItem('defaultUsername') === 'Anonymous Guest') {
                            this.authUser = 'Anonymous Guest';
                        }
                        else {
                            this.authenticateUser(
                                localStorage.getItem('defaultUsername'),
                                localStorage.getItem('defaultUserId')
                            );
                        }
                    }
                    else {
                        this.authUser = 'Anonymous Guest';
                    }
                }
            },


            authUser(newVal) {
                if (newVal.length > 0) {
                    localStorage.setItem('defaultUsername', newVal);
                    this.fetchStories();
                    this.fetchSuggestedAccounts();
                    this.fetchPosts('initial');
                }
            },


            authUserId(newVal) {
                localStorage.setItem('defaultUserId', newVal);
            }
        }
    }

</script>

// angularFrontend1/src/app/HomePage.component.ts
import { Footer } from '../components/Footer.component';
import { LeftSidebar } from '../components/LeftSidebar.component';
import { ErrorPopup } from '../components/Popups/ErrorPopup.component';
import { UserIcon } from '../components/UserIcon.component';

import { AboutAccountPopup } from '../components/Popups/AboutAccountPopup.component';
import { LeftSidebarPopup } from '../components/Popups/LeftSidebarPopup.component';
import { ThreeDotsPopup } from '../components/Popups/ThreeDotsPopup.component';

import { CommonModule } from '@angular/common';
import { Component, SimpleChanges } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { LikersPopup } from '../components/Popups/LikersPopup.component';
import { SendPostPopup } from '../components/Popups/SendPostPopup.component';
import { UserBar } from '../components/UserBar.component';


@Component({
  selector: 'HomePage',
  standalone: true,
  imports: [
    CommonModule, LeftSidebar, LeftSidebarPopup, Footer, ErrorPopup, ThreeDotsPopup, UserIcon, AboutAccountPopup, UserBar,
    LikersPopup, SendPostPopup
  ],
  templateUrl: './HomePage.component.html',
  styleUrl: '../HomePageStyles.css'
})
export class HomePage {
  authUser:string = '';
  authUserId:number = -1;

  originalURL:string = '';
  numTimesRouteParamsWasWatched:number = 0;

  displayLeftSidebarPopup:boolean = false;

  displayErrorPopup:boolean = false;
  errorPopupMessage:string = '';

  displayThreeDotsPopup:boolean = false;
  threeDotsPopupPostDetails:any = {};

  displayAboutAccountPopup:boolean = false;
  aboutAccountUsername:string = '';
  aboutAccountUserId:number  = -1;
  aboutAccountUserIsVerified:boolean = false;
  aboutAccountUserHasStories:boolean = false;
  aboutAccountUserHasUnseenStory:boolean = false;
  aboutAccountUserProfilePhoto:string|null = null;

  displayLikersPopup:boolean = false;
  likersPopupIdOfPostOrComment:string|number = '';

  displaySendPostPopup:boolean = false;
  sendPostPopupOverallPostId:string = '';

  displayCommentsPopup:boolean = false;

  displayStoryViewer:boolean = false;
  storyViewerUsername:string = '';
  storyViewerIsFromStoriesSection:boolean = false;

  usersAndTheirRelevantInfo:any = {};

  cachedMessageSendingSuggestions:any = {};

  orderedListOfPosts:Array<any> = [];

  constructor(private route: ActivatedRoute) { }


  ngOnInit(): void {
    this.originalURL = window.location.href;

    const username = this.route.snapshot.paramMap.get('username');
    if(username !== null && localStorage.getItem('defaultUsername') !== username) {
        this.authenticateUser(username, null);
    }
    else if(localStorage.getItem('defaultUsername')) {
        if (localStorage.getItem('defaultUsername') === 'Anonymous Guest') {
            this.authUser = 'Anonymous Guest';
        }
        else {
            this.authenticateUser(
              localStorage.getItem('defaultUsername') ?? '',
              parseInt(localStorage.getItem('defaultUserId') ?? '-1')
            );
        }
    }
    else {
        this.authUser = 'Anonymous Guest';
    }
  }


  ngOnChanges(changes: SimpleChanges): void {
    if (changes['authUser']) {
      const newVal = changes['authUser'].currentValue;
      if (newVal && newVal.length > 0) {
        localStorage.setItem('defaultUsername', newVal);
        this.fetchStories();
        this.fetchSuggestedAccounts();
        this.fetchPosts('initial');
      }
    }

    if (changes['authUserId']) {
      const newVal = changes['authUserId'].currentValue;
      if (newVal) {
        localStorage.setItem('defaultUserId', newVal);
      }
    }
  }


  async authenticateUser(username:string , userId:number|null) {
    if (userId == null) {
      try {
        const response = await fetch('http://34.111.89.101/api/Home-Page/laravelBackend1/graphql', {
          method: 'POST',
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify({
            query: `query getUserIdOfUsername($username: String!) {
              getUserIdOfUsername(username: $username)
            }`,
            variables: {
              username: username
            }
          })
        });
        if (!response.ok) {
          this.authUser = 'Anonymous Guest';
          
          throw new Error(
            `The laravelBackend1 server had trouble getting the user-id of username ${username}`
          );
        }
        userId = await response.json();
        this.authUserId = userId ?? -1;
      }
      catch {
        this.authUser = 'Anonymous Guest';

        throw new Error(
          `There was trouble connecting to the laravelBackend1 server to get the user-id of username ${username}`
        );
      }
    }
    else {
        this.authUserId = userId;
    }

    try {
      const response1 = await fetch(`http://34.111.89.101/api/Home-Page/expressJSBackend1/authenticateUser
      /${userId}`, { credentials: 'include' });
      if (!response1.ok) {
        this.authUser = 'Anonymous Guest';
        this.authUserId = -1;

        throw new Error(
          `The expressJSBackend1 server had trouble verifying you as having the proper credentials to be 
          logged in as user ${userId}`
        );
      }

      this.authUser = username;
    }
    catch {
      this.authUser = 'Anonymous Guest';
      this.authUserId = -1;

      throw new Error(
        `There was trouble connecting to the expressJSBackend1 server to verify you as having the proper
        credentials to be logged in as user ${userId}`
      );
    }
  }


  async fetchStories() {

  }


  async fetchSuggestedAccounts() {

  }


  async fetchPosts(initialOrAdditionalText:string) {
    initialOrAdditionalText;
  }


  hidePost() {
    this.orderedListOfPosts = this.orderedListOfPosts.filter(
        postDetails => (postDetails.overallPostId !== this.threeDotsPopupPostDetails.overallPostId)
    );
    this.displayThreeDotsPopup = false;
    this.displayCommentsPopup = false;
  }


  updateUsersAndTheirRelevantInfo(newUsersAndTheirRelevantInfo:any) {
    this.usersAndTheirRelevantInfo = newUsersAndTheirRelevantInfo;
  }


  updateCachedMessageSendingSuggestions(newCachedMessageSendingSuggestions:any) {
    this.cachedMessageSendingSuggestions = newCachedMessageSendingSuggestions;
  }


  showErrorPopup(newErrorPopupMessage:string) {
    this.errorPopupMessage = newErrorPopupMessage;
    this.displayErrorPopup = true;
  }


  showAboutAccountPopup(usernameAndIdInfo: { username: string; userId: number }) {
    const newAboutAccountUsername = usernameAndIdInfo.username;
    const newAboutAccountUserId = usernameAndIdInfo.userId;

    this.aboutAccountUsername = newAboutAccountUsername;

    this.aboutAccountUserIsVerified = 
      newAboutAccountUserId in this.usersAndTheirRelevantInfo &&
      'isVerified' in this.usersAndTheirRelevantInfo[newAboutAccountUserId]
      ? this.usersAndTheirRelevantInfo[newAboutAccountUserId].isVerified
      : false;

    this.aboutAccountUserHasStories = 
      newAboutAccountUserId in this.usersAndTheirRelevantInfo &&
      'hasStories' in this.usersAndTheirRelevantInfo[newAboutAccountUserId]
      ? this.usersAndTheirRelevantInfo[newAboutAccountUserId].hasStories
      : false;

    this.aboutAccountUserHasUnseenStory = 
      newAboutAccountUserId in this.usersAndTheirRelevantInfo &&
      'hasUnseenStory' in this.usersAndTheirRelevantInfo[newAboutAccountUserId]
      ? this.usersAndTheirRelevantInfo[newAboutAccountUserId].hasUnseenStory
      : false;

    this.aboutAccountUserProfilePhoto = 
      newAboutAccountUserId in this.usersAndTheirRelevantInfo &&
      'profilePhoto' in this.usersAndTheirRelevantInfo[newAboutAccountUserId]
      ? this.usersAndTheirRelevantInfo[newAboutAccountUserId].profilePhoto
      : 'images/defaultPfp.png';

    this.displayAboutAccountPopup = true;
  }


  showStoryViewer(infoForStoryViewer:{username: string, isFromStoriesSection: boolean}) {
    this.storyViewerUsername = infoForStoryViewer.username;
    this.storyViewerIsFromStoriesSection = infoForStoryViewer.isFromStoriesSection;
    this.displayStoryViewer = true;
  }


  showLikersPopup(newLikersPopupIdOfPostOrComment:string|number) {
    this.likersPopupIdOfPostOrComment = newLikersPopupIdOfPostOrComment;
    this.displayLikersPopup = true;
  }


  showSendPostPopup(newSendPostPopupOverallPostId:string) {
    this.sendPostPopupOverallPostId = newSendPostPopupOverallPostId;
    this.displaySendPostPopup = true;
  }


  toggleDisplayLeftSidebarPopup() {
    this.displayLeftSidebarPopup = !this.displayLeftSidebarPopup;
  }


  closeAllPopups() {
    if(!(this.displayCommentsPopup && (this.displayThreeDotsPopup || this.displayAboutAccountPopup ||
    this.displayErrorPopup || this.displayLikersPopup || this.displaySendPostPopup))) {
      this.displayCommentsPopup = false;
    }

    this.displayLeftSidebarPopup = false;
    this.displayErrorPopup = false;
    this.displayThreeDotsPopup = false;
    this.displayAboutAccountPopup = false;
    this.displayLikersPopup = false;
    this.displaySendPostPopup = false;
  }


  closeThreeDotsPopup() {
    this.displayThreeDotsPopup = false;
  }


  closeAboutAccountPopup() {
    this.displayAboutAccountPopup = false;
  }


  closeErrorPopup() {
    this.displayErrorPopup = false;
  }


  closeLikersPopup () {
    this.displayLikersPopup = false;
  }


  closeSendPostPopup() {
    this.displaySendPostPopup = false;
  }


  addRelevantInfoToUser(requiredInfo:{userId: number, userFieldsAndTheirValues:any}) {
    const { userId, userFieldsAndTheirValues }  = requiredInfo;
    if (!(userId in this.usersAndTheirRelevantInfo)) {
      this.usersAndTheirRelevantInfo[userId] = {};
    }

    for(let field of Object.keys(userFieldsAndTheirValues)) {
      this.usersAndTheirRelevantInfo[userId][field] = userFieldsAndTheirValues[field];
    }
  }
}

<LeftSidebar
    [profilePhoto]="'images/defaultPfp.png'"
    [displayPopup]="displayLeftSidebarPopup"
    [authUserIsAnonymousGuest]="authUserId == -1"
    (toggleDisplayLeftSidebarPopup)="toggleDisplayLeftSidebarPopup()"
/>

<div style="position: absolute; left: 24%;">
    
</div>

<img [src]="'images/blackScreen.png'" *ngIf="displayLeftSidebarPopup || displayErrorPopup || displayThreeDotsPopup ||
displayAboutAccountPopup || displayCommentsPopup || displayLikersPopup || displaySendPostPopup" (click)="closeAllPopups()"
style="position: fixed; top: 0%; left: 0%; width: 100%; height: 100%; opacity: 0.7; z-index: 2;"/>

<div *ngIf="displayAboutAccountPopup" [ngStyle]="{position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%,
-50%)', zIndex: displayStoryViewer ? '1' : '3'}">
    <AboutAccountPopup
        [authUserId]="authUserId"
        [userId]="aboutAccountUserId"
        [username]="aboutAccountUsername"
        [authUser]="authUser"
        [userPfp]="aboutAccountUserProfilePhoto"
        [userIsVerified]="aboutAccountUserIsVerified"
        [userHasStories]="aboutAccountUserHasStories"
        [userHasUnseenStory]="aboutAccountUserHasUnseenStory"
        [usersAndTheirRelevantInfo]="usersAndTheirRelevantInfo"
        (addRelevantInfoToUser)="addRelevantInfoToUser($event)"
        (closePopup)="closeAboutAccountPopup()"
        (showStoryViewer)="showStoryViewer($event)"
    />
</div>

<div *ngIf="displayLeftSidebarPopup" [ngStyle]="{position: 'fixed', bottom: '10%', left: '1%', zIndex: displayErrorPopup ?
'1' : '3'}">
    <LeftSidebarPopup
        [authUserId]="authUserId"
        [originalURL]="originalURL"
        (showErrorPopup)="showErrorPopup($event)"
    />
</div>

<div *ngIf="displayThreeDotsPopup" [ngStyle]="{position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%,
-50%)', zIndex: displayErrorPopup ? '1' : '3'}">
    <ThreeDotsPopup
        [authUserId]="authUserId"
        [postDetails]="threeDotsPopupPostDetails"
        (hidePost)="hidePost()"
        (showErrorPopup)="showErrorPopup($event)"
        (closePopup)="closeThreeDotsPopup()"
        (showAboutAccountPopup)="showAboutAccountPopup($event)"
    />
</div>

<div *ngIf="displayLikersPopup" [ngStyle]="{position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%,
-50%)', zIndex: displayErrorPopup ? '1' : '3'}">
    <LikersPopup
        [idOfPostOrComment]="likersPopupIdOfPostOrComment"
        [authUserId]="authUserId"
        [usersAndTheirRelevantInfo]="usersAndTheirRelevantInfo" 
        (closePopup)="closeLikersPopup()"
        (showErrorPopup)="showErrorPopup($event)"
        (updateUsersAndTheirRelevantInfo)="updateUsersAndTheirRelevantInfo($event)"
    />
</div>

<div *ngIf="displaySendPostPopup" [ngStyle]="{position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%,
-50%)', zIndex: displayErrorPopup ? '1' : '3'}">
    <SendPostPopup
        [authUserId]="authUserId"
        [overallPostId]="sendPostPopupOverallPostId"
        [usersAndTheirRelevantInfo]="usersAndTheirRelevantInfo"
        [cachedMessageSendingSuggestions]="cachedMessageSendingSuggestions"
        (updateUsersAndTheirRelevantInfo)="updateUsersAndTheirRelevantInfo($event)"
        (updateCachedMessageSendingSuggestions)="updateCachedMessageSendingSuggestions($event)"
        (showErrorPopup)="showErrorPopup($event)"
        (closePopup)="closeSendPostPopup()"
    />
</div>

<div *ngIf="displayErrorPopup" style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 3;">
    <ErrorPopup
        [errorMessage]="errorPopupMessage"
        (closePopup)="closeErrorPopup()"
    />
</div>
